"""empty message

Revision ID: 9d9f2f2fb96d
Revises: 57ee798595d7
Create Date: 2024-02-23 13:16:27.818881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9f2f2fb96d'
down_revision = '57ee798595d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzaImages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pizzaImg', sa.String(), nullable=False))
        batch_op.alter_column('pizza_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('pizza_img')

    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.drop_column('pizzaImg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pizzaImg', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('pizzaImages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pizza_img', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('pizza_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('pizzaImg')

    # ### end Alembic commands ###